version: '3'
services:
  mosquitto:
    image: "eclipse-mosquitto"
    container_name: "poc-quarkus-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
  consul:
    image: "consul"
    container_name: "poc-quarkus-consul"
    ports:
      - "8500:8500"
    entrypoint:
      - consul
      - agent
      - -dev
      - -client=0.0.0.0
      - -bind=0.0.0.0
  mongodb:
    image: mongo
    container_name: "poc-quarkus-mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin-user"
      MONGO_INITDB_ROOT_PASSWORD: "admin-password"
      MONGO_INITDB_DATABASE: "poc-quarkus-db"
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  db: